import { Router } from "express";
import authRouter from "./auth";
import dealersRouter from "./dealers";
import ordersRouter from "./orders";
import productsRouter, { productCategoriesRouter } from "./products";
import recommendationsRouter from "./recommendations";
import dispatchesRouter from "./dispatches";
import inventoryRouter from "./inventory";
import invoicesRouter from "./invoices";
import creditNotesRouter from "./creditNotes";
import paymentsRouter from "./payments";
import zonesRouter from "./zones";
import dashboardRouter from "./dashboard";
import reportsRouter from "./reports";
import fieldRouter from "./field";
import emailsRouter from "./emails";
import usersRouter from "./users";
import settingsRouter from "./settings";
import cronRouter from "./cron";
import daichiSyncRouter from "./daichiSync";
import daichiDealersRouter from "./daichiDealers";
import exportsRouter from "./exports";

export const apiRouter = Router();

apiRouter.use("/auth", authRouter);
apiRouter.use("/dealers", dealersRouter);
apiRouter.use("/orders", ordersRouter);
apiRouter.use("/products", productsRouter);
apiRouter.use("/product-categories", productCategoriesRouter);
apiRouter.use("/recommendations", recommendationsRouter);
apiRouter.use("/dispatches", dispatchesRouter);
apiRouter.use("/inventory", inventoryRouter);
apiRouter.use("/invoices", invoicesRouter);
apiRouter.use("/credit-notes", creditNotesRouter);
apiRouter.use("/payments", paymentsRouter);
apiRouter.use("/zones", zonesRouter);
apiRouter.use("/dashboard", dashboardRouter);
apiRouter.use("/reports", reportsRouter);
apiRouter.use(fieldRouter);
apiRouter.use("/emails", emailsRouter);
apiRouter.use("/users", usersRouter);
apiRouter.use("/settings", settingsRouter);
apiRouter.use("/cron", cronRouter);
apiRouter.use("/sync/daichi", daichiSyncRouter);
apiRouter.use("/daichi-dealers", daichiDealersRouter);
apiRouter.use("/exports", exportsRouter);
