import { Router } from "express";
import authRouter from "./auth";
import dealersRouter from "./dealers";
import productsRouter, { productCategoriesRouter } from "./products";
import ordersRouter from "./orders";
import invoicesRouter from "./invoices";
import creditNotesRouter from "./creditNotes";
import dashboardRouter from "./dashboard";
import recommendationsRouter from "./recommendations";
import dispatchesRouter from "./dispatches";
import fieldRouter from "./field";
import zonesRouter from "./zones";
import inventoryRouter from "./inventory";
import paymentsRouter from "./payments";
import usersRouter from "./users";
import settingsRouter from "./settings";
import reportsRouter from "./reports";
import emailsRouter from "./emails";
import logisticsRouter from "./logistics";

export const mongoApiRouter = Router();

mongoApiRouter.use("/auth", authRouter);
mongoApiRouter.use("/dealers", dealersRouter);
mongoApiRouter.use("/products", productsRouter);
mongoApiRouter.use("/product-categories", productCategoriesRouter);
mongoApiRouter.use("/orders", ordersRouter);
mongoApiRouter.use("/invoices", invoicesRouter);
mongoApiRouter.use("/credit-notes", creditNotesRouter);
mongoApiRouter.use("/dashboard", dashboardRouter);
mongoApiRouter.use("/recommendations", recommendationsRouter);
mongoApiRouter.use("/dispatches", dispatchesRouter);
mongoApiRouter.use("/zones", zonesRouter);
mongoApiRouter.use("/inventory", inventoryRouter);
mongoApiRouter.use("/payments", paymentsRouter);
mongoApiRouter.use("/users", usersRouter);
mongoApiRouter.use("/settings", settingsRouter);
mongoApiRouter.use("/reports", reportsRouter);
mongoApiRouter.use("/emails", emailsRouter);
mongoApiRouter.use("/logistics", logisticsRouter);
mongoApiRouter.use(fieldRouter);
